apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-saas-mvp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/monicamarshall/ai-saas-mvp.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


---
apiVersion: v1
kind: Service
metadata:
  name: ai-saas-mvp
spec:
  type: LoadBalancer
  selector:
    app: ai-saas-mvp
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP

# Optional: Ingress example (requires an ingress controller)
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ai-saas-mvp
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#   - host: mvp.example.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: ai-saas-mvp
#             port:
#               number: 80
