apiVersion: v1
kind: Namespace
metadata:
  name: ai-saas
  labels:
    app.kubernetes.io/name: ai-saas-mvp
    app.kubernetes.io/part-of: ai-saas-mvp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-saas-mvp
  namespace: ai-saas
  labels:
    app.kubernetes.io/name: ai-saas-mvp
    app.kubernetes.io/part-of: ai-saas-mvp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-saas-mvp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-saas-mvp
        app.kubernetes.io/part-of: ai-saas-mvp
    spec:
      containers:
      - name: ai-saas-mvp-container
        image: docker.io/monicamarshall/ai-saas-mvp:16
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8090
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ai-saas-mvp
  namespace: ai-saas
  labels:
    app.kubernetes.io/name: ai-saas-mvp
    app.kubernetes.io/part-of: ai-saas-mvp
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ai-saas-mvp
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
